export * from './header/Header'
export * from './movieContainer/Movies'
export * from './movieContainer/MovieCard'
export * from './searchComponent/Search'
export * from './genreContainer/Genres'
export * from './genreContainer/Genre'